VotingProject/VotingContact/urls.py
from django.contrib import admin
from django.urls import include,path
from VotingContact import views


app_name = 'votingcontact'
urlpatterns = [
    path('', views.contact, name='contact'),
    path('contact/', views.contact, name='contact'),
]

VotingProject/VotingHome/urls.py
from django.contrib import admin
from django.urls import include,path
from VotingHome import views

app_name = 'votinghome'
urlpatterns = [
    path('', views.signup, name='signup'),
    path('login-signup/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

VotingProject/VotingPolls/urls.py

# urls.py
from django.urls import path
from . import views

app_name = 'votingpolls'
urlpatterns = [
    path('', views.index, name='index'),
    # path('polls/', views.polls, name='polls'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    # path('all_results/', views.all_results, name='all_results'),
]


VotingProject/VotingProject/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('votinghome/', include('VotingHome.urls')),
    path('votingcontact/', include('VotingContact.urls')),
    path('', include('VotingWebsite.urls')),
    path('votingresult/', include('VotingResult.urls')),
    path('votingpolls/', include('VotingPolls.urls')),
    
]

VotingProject/VotingWebsite/urls.py
from django.contrib import admin
from django.urls import include,path
from VotingWebsite import views

app_name = 'votingwebsite'
urlpatterns = [
    path('', views.website, name='website'),
#     path('website/', views.website, name='website'),
]


VotingProject/VotingPolls/models.py
# models.py
from django.db import models
from datetime import datetime
from django.utils import timezone
from datetime import timedelta
from django.contrib.auth.models import User

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    # pub_date = models.DateTimeField(default=timezone.now)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text
    
class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
    voted_at = models.DateTimeField(auto_now_add=True)

    # class Meta:
    #     unique_together = ('user', 'question')

    def __str__(self):
        return f"{self.user} voted on {self.question}"

VotingProject/templates/pages/contact.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Contact US Section</title>
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css">
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/fontawesome.min.css">
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.css">
	<link href="https://fonts.googleapis.com/css?family=Oswald:400,700|Roboto&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'contact.css' %}">
</head>

<body>
  {% include "pages/navbar.html" %}
	<div>
	<!-- START CONTACT SECTION -->
	<div class="container">
		<div class="section-contact">
			<div class="row justify-content-center">
				<div class="col-12 col-lg-10 col-xl-8">
					<div class="header-section text-center">
						<h2 class="title">Get In Touch
							<span class="dot"></span>
							<span class="big-title">CONTACT</span>
						</h2>
						<p class="description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean consectetur commodo risus, nec pellentesque turpis efficitur non.</p>
						
					</div>
				</div>
			</div>
			<div class="form-contact">
				{% if messages %}
                        <div class="messages">
                            {% for message in messages %}
                                <div class="alert alert-success">
                                    {{ message }}
                                </div>
                            {% endfor %}
                        </div>
                    {% endif %}
				<form id="form" method="POST" action="{% url 'votingcontact:contact' %}">
					{% csrf_token %}
					<div class="row">
						<div class="col-md-6">
							<div class="single-input">
								<i class="fas fa-user"></i>
								<input type="text" name="name" placeholder="ENTER YOUR NAME">
							</div>
						</div>
						<div class="col-md-6">
							<div class="single-input">
								<i class="fas fa-envelope"></i>
								<input type="email" name="email" placeholder="ENTER YOUR EMAIL">
							</div>
						</div>
						<div class="col-md-6">
							<div class="single-input">
								<i class="fas fa-phone"></i>
								<input type="number" name="phone" placeholder="ENTER YOUR PHONE NUMBER">
							</div>
						</div>
						<div class="col-md-6">
							<div class="single-input">
								<i class="fas fa-check"></i>
								<input type="text" name="subject" placeholder="ENTER YOUR SUBJECT">
							</div>
						</div>
						<div class="col-12">
							<div class="single-input">
								<i class="fas fa-comment-dots"></i>
								<textarea name="message" placeholder="ENTER YOUR MESSAGE"></textarea>
							</div>
						</div>
						<div class="col-12">
							<div class="submit-input text-center">
								<input type="submit" name="submit" value="SUBMIT NOW">
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
	<!-- / END CONTACT SECTION -->
	</div>
</body>
</html>

VotingProject/templates/pages/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'home.css' %}">
</head>
<body>
<h2>VoteMinder</h2>
<div class="container {% if signup_active %}right-panel-active{% endif %}" id="container">
	<div class="form-container sign-up-container">
		<form id="form" method="POST" action="{% url 'votinghome:signup' %}">
			{% csrf_token %}
			<h1>Create Account</h1>
			<div class="social-container">
				<a href="https://www.facebook.com/login.php/" class="social"><i class="fab fa-facebook-f"></i></a>
				<a href="#" class="social"><i class="fab fa-google-plus-g"></i></a>
				<a href="#" class="social"><i class="fab fa-linkedin-in"></i></a>
			</div>
			<span>or use your email for registration</span>
			<input type="text" name="name" placeholder="Name" />
			<input type="email" name="email" placeholder="Email" />
			<input type="password" name="password" placeholder="Password" />
			<button type="submit">Sign Up</button>
			{% if messages %}
                <div>
                    {% for message in messages %}
						<div class="alert {% if message.tags == 'error' %}alert-error{% else %}alert-success{% endif %}">
							{{ message }}
						</div>
                    {% endfor %}
                </div>
            {% endif %}
		</form>
	</div>
	<div class="form-container sign-in-container">
		<form id="form" method="POST" action="{% url 'votinghome:login' %}">
			{% csrf_token %}
			<h1>Sign in</h1>
			<div class="social-container">
				<a href="#" class="social"><i class="fab fa-facebook-f"></i></a>
				<a href="#" class="social"><i class="fab fa-google-plus-g"></i></a>
				<a href="#" class="social"><i class="fab fa-linkedin-in"></i></a>
			</div>
			<span>or use your account</span>
			<input type="email" name="email" placeholder="Email" />
			<input type="password" name="password" placeholder="Password" />
			<a href="#">Forgot your password?</a>
			<button type="submit">Sign In</button>
			{% if messages %}
                <div>
                    {% for message in messages %}
						<div class="alert {% if message.tags == 'error' %}alert-error{% else %}alert-success{% endif %}">
							{{ message }}
						</div>
                    {% endfor %}
                </div>
            {% endif %}
		</form>
	</div>
	<div class="overlay-container">
		<div class="overlay">
			<div class="overlay-panel overlay-left">
				<h1>Welcome Back!</h1>
				<p>To keep connected with us please login with your personal info</p>
				<button class="ghost" id="signIn"><a href="{% url 'votinghome:login' %}" class="ghost-1">Sign In</a></button>
				
			</div>
			<div class="overlay-panel overlay-right">
				<h1>Hello, Friend!</h1>
				<p>Enter your personal details and start journey with us</p>
				<button class="ghost" id="signUp"><a href="{% url 'votinghome:signup' %}" class="ghost-1">Sign Up</a></button>
			</div>
		</div>
	</div>
</div>
  
<script>
   const signUpButton = document.getElementById('signUp');
   const signInButton = document.getElementById('signIn');
   const container = document.getElementById('container');

   	signUpButton.addEventListener('click', () => {
	container.classList.add("right-panel-active");	
	window.location.href = "{% url 'votinghome:signup' %}";
	});

	signInButton.addEventListener('click', () => {
		container.classList.remove("right-panel-active");
		window.location.href = "{% url 'votinghome:login' %}";
	});
	document.getElementById('signup-form').addEventListener('submit', function(event) {
		const name = document.getElementById('signup-name').value;
		const email = document.getElementById('signup-email').value;
		const password = document.getElementById('signup-password').value;

    if (!name || !email || !password) {
        event.preventDefault();
        <div class = "please">
			alert('Please fill in all fields.');
		</div>
    }
});
</script>
</body>
</html>

VotingProject/templates/pages/navbar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'navbar.css' %}">
    <title>Vote Section</title>
</head>
<body>
  <nav class="navbar">
    <span class="navbar-toggle" id="js-navbar-toggle">
            <i class="fas fa-bars"></i>
        </span>
    <a href="{% url 'votingwebsite:website' %}" class="logo">VoteMinder</a>
    <ul class="main-nav" id="js-menu">
      <li>
        <a href="{% url 'votingwebsite:website' %}" class="nav-links">Home</a>
      </li>
      <li>
        <a href="{% url 'votingcontact:contact' %}" class="nav-links">Contact</a>
      </li>
      {% if user.is_authenticated %}
      <li>
        <a href="{% url 'votingpolls:index' %}" class="nav-links">Vote Now</a>
      </li>
        <li>
          <a href="{% url 'votinghome:logout' %}" class="nav-links">Logout</a>
        </li>
        
        {% else %}
        <li>
          <a href="{% url 'votinghome:login' %}" class="nav-links">Login</a>
        </li>
        <li>
          <a href="{% url 'votinghome:signup' %}" class="nav-links">Sign Up</a>
        </li>
      {% endif %}
    </ul>
  </nav>
  <script>
    let mainNav = document.getElementById("js-menu");
    let navBarToggle = document.getElementById("js-navbar-toggle");

    navBarToggle.addEventListener("click", function() {
    mainNav.classList.toggle("active");
    });
</script>
</body>
</html>

VotingProject/templates/pages/result.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls.css' %}">
{% include "pages/navbar.html" %}
<div class="container">
    <h1 class="heading">Results for All Questions</h1>
    {% for question in questions %}
    <section class="results-section">
        <h2>{{ question.question_text }}</h2>
        <ul>
            {% for choice in question.choice_set.all %}
                <li>{{ choice.choice_text }}: {{ choice.votes }} votes</li>
            {% endfor %}
        </ul>
    </section>
    {% endfor %}
</div>

VotingProject/templates/pages/website.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Main Page</title>
    <link rel="stylesheet" href="{% static 'website.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
  {% include "pages/navbar.html" %}
    <div id="home" class="container-fluid fill dark-gray-background">
      <h1 class="center text-center">
        <p>"Voice Your Choice: Empowering Your Vote, Shaping Our Future!" </p>
      </h1>
    </div>
  </div>

  <div id="about" class="container-fluid">
    <h2 class="text-uppercase dark-gray-font">About Us</h2>
    <div class="container">
      <div class="row">
        <div class="col-md-5 col-md-offset-1 col-sm-12">
          <p class="dark-gray-font text-justify">
            "Elections represent the cornerstone of democracy, providing citizens with the opportunity to exercise their right to vote and choose representatives who will govern on their behalf. Through elections, individuals contribute to the shaping of policies, laws, and the overall trajectory of their society. This participatory process fosters accountability, transparency, and civic engagement, reinforcing the democratic principles of equality, freedom, and justice."
          </p>
          <p class="dark-gray-font text-justify">
            In India, elections unfold against a backdrop of diversity, complexity, and vibrancy. From bustling urban centers to remote rural villages, the electoral landscape is characterized by a rich tapestry of cultures, languages, and traditions.
          </p>
        </div>
        <div class="col-md-5 col-sm-12">
          <p class="dark-gray-font text-justify">
            Political campaigns energize the nation, as candidates traverse vast distances, addressing diverse constituencies and engaging in spirited debates. Despite challenges such as logistical hurdles and occasional instances of malpractice, Indian elections exemplify the resilience of democracy, with millions of voters exercising their franchise to shape the country's destiny.</p>
          <p class="dark-gray-font text-justify">
            In the run-up to elections, the political atmosphere in India becomes charged with anticipation and fervor, as parties vie for power and voters weigh their options. Campaign rallies, public speeches, and media coverage amplify the democratic discourse, fostering a sense of civic duty and political awareness among the populace.
          </p>
        </div>
      </div>
    </div>
  </div>

  <div id="projects" class="container-fluid light-white-font">
    <h2 class="text-uppercase dark-gray-font">NEWS UPDATES</h2>
    <div class="container dark-gray-font">
      <div class="row">

        <div class="col-md-4">
          <div class="panel panel-default fixed-width center-block">
            <div class="panel-body">
              <a href="https://tmp.eci.gov.in/electoral-roll" target="Electoral Fraud">
                <img class="img-responsive center-block" src="{% static 'img/img1.jpg' %}" />
              </a>
            </div>
            <div class="panel-footer">
              <h3>Electoral Fraud</h3>
              <p> Concerns about electoral fraud, including vote rigging, booth capturing, and tampering with electronic voting machines (EVMs), have been reported in past elections.</p>
            </div>
          </div>
        </div>

        <div class="col-md-4">
          <div class="panel panel-default fixed-width center-block">
            <div class="panel-body">
              <a href="https://electoralsearch.eci.gov.in/" target="coderbits">
                <img class="img-responsive center-block" src="{% static 'img/img2.jpg' %}" />
              </a>             
            </div>
            <div class="panel-footer">
              <h3>Voter Suppression: </h3>
              <p> Instances of voter suppression, such as intimidation of voters, coercion, and disenfranchisement, have been reported in some areas, particularly those affected by political violence or communal tensions.</p>
            </div>
          </div>
        </div>

        <div class="col-md-4">
          <div class="panel panel-default fixed-width center-block">
            <div class="panel-body">
              <a href="https://www.hindustantimes.com/india-news/extortion-scheme-biggest-scam-oppn-slams-pm-modis-electoral-bonds-defence-101713189317079.html" target="file-appender">
                <img class="img-responsive center-block" src="{% static 'img/img3.jpg' %}" />
              </a>
            </div>
            <div class="panel-footer">
              <h3>Money Power</h3>
              <p>The influence of money in elections, including the use of illegal funds for campaigning, buying votes, and influencing political outcomes, remains a significant concern.</p>
            </div>
          </div>
        </div>

      </div>

      <div class="row">

        <div class="col-md-4">
          <div class="panel panel-default fixed-width center-block">
            <div class="panel-body">
              <a href="https://www.researchgate.net/publication/333719218_Electoral_Violence_Threats_and_Security_Problems_and_Prospects_for_Indian_Democracy" target="objectiveng">
                <img class="img-responsive center-block" src="{% static 'img/img4.jpg' %}" />
              </a>
            </div>
            <div class="panel-footer">
              <h3>Political Violence</h3>
              <p> Incidents of political violence, clashes between rival party supporters, and intimidation of candidates have been reported in some regions, particularly during the election campaign period.</p>
            </div>
          </div>
        </div>

        <div class="col-md-4">
          <div class="panel panel-default fixed-width center-block">
            <div class="panel-body">
              <a href="https://www.reuters.com/world/india/indias-lok-sabha-election-2024-main-political-parties-candidates-2024-04-16/" target="randomquotegen">
                <img class="img-responsive center-block" src="{% static 'img/img5.jpg' %}" />
              </a>
            </div>
            <div class="panel-footer">
              <h3>Identity Politics</h3>
              <p> The use of identity-based politics, including religious, caste, and regional considerations, to polarize voters and consolidate electoral support remains a contentious issue in Indian elections.</p>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="panel panel-default fixed-width center-block">
            <div class="panel-body">
              <a href="https://www.reuters.com/world/india/indias-lok-sabha-election-2024-main-political-parties-candidates-2024-04-16/" target="coderbits">
                <img class="img-responsive center-block" src="{% static 'img/img6.jpg' %}" />
              </a>              </div>
            <div class="panel-footer">
              <h3>Misinformation</h3>
              <p> "False information on social media distorts voter views, erodes trust, and undermines election fairness, threatening overall electoral integrity."</p>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>

  <div id="about" class="container-fluid">
    <h2 class="text-uppercase dark-gray-font">Current Issues</h2>
    <div class="container">
      <div class="row">
        <div class="col-md-5 col-md-offset-1 col-sm-12">
          <p class="dark-gray-font text-justify">
            <strong>COVID-19 Pandemic:</strong> India continues to battle the COVID-19 pandemic, focusing on vaccination drives, managing healthcare resources, and balancing public health measures with economic activities.<br>
            <strong>Economic Challenges:</strong> India faces economic challenges, including high inflation rates, unemployment, and the impact of the pandemic on various sectors such as tourism, hospitality, and small businesses.<br>
            <strong>Farmers' Protests:</strong> Farmers' protests against new agricultural laws have been ongoing, with farmers demanding the repeal of the laws and assurance of minimum support prices (MSP) for their produce.<br>
          </p>
        </div>
        <div class="col-md-5 col-sm-12">
          <p class="dark-gray-font text-justify">
            <strong>Political Landscape:</strong> The political landscape in India remains dynamic, with state elections, coalition politics, and debates on issues such as secularism, federalism, and governance dominating public discourse.<br>
            <strong>Environmental Concerns:</strong> India grapples with environmental challenges, including air and water pollution, deforestation, and climate change impacts. Efforts to address these issues include renewable energy initiatives, pollution control measures, and conservation efforts.<br>
            <strong>Social Issues:</strong> Social issues like caste discrimination, gender inequality, and limited access to education and healthcare persist in India despite efforts to address them through policy and grassroots initiatives.
          </p>
        </div>
      </div>
    </div>
  </div>

  <div id="aboutstep" class="container-fluid">
    <h2 class="text-uppercase dark-gray-font">Steps to Vote</h2>
    <div class="container">
      <div class="row">
          <p class="dark-gray-font text-justify">
            1.Register Online:Visit the official election website to register as an online voter. Follow the provided instructions to enter your details and verify your identity.<br>
            2.Login on Voting Day:On the election day, log in to the online voting platform using your registered credentials.<br>
            3.Access Your Ballot: Once logged in, access your electronic ballot. Review the list of candidates or options available for voting.<br>
            4.Make Your Selections: Choose your preferred candidate or option by clicking or tapping on the corresponding button or checkbox.<br>
            5.Review Your Choices: Before submitting, review your selections to ensure they are accurate.<br>
            6.Submit Your Vote: Submit your vote electronically through the platform.<br>
            7.Confirmation of Submission: Receive a confirmation of your vote submission via an on-screen message.<br>
            8.Ensure Security: Rest assured that the online voting platform incorporates various security measures to protect the integrity and confidentiality of your vote.<br>
          </p>
        </div>
        </div>
        </div>
  <div id="contact" class="footer">
    <div class="container">
      <div class="row">
        {% if user.is_authenticated %}
        <button type="button" name="email-btn" class="btn btn-default middle-blue-background center-block email">
            <a href="{% url 'votingpolls:index' %}" class="text-center text-uppercase">
                <i class="fa fa-envelope"></i>Vote Now!
            </a>
        </button>
        {% else %}
            <button type="button" name="email-btn" class="btn btn-default middle-blue-background center-block email">
                <a href="{% url 'votinghome:login' %}?next={% url 'votingpolls:index' %}" class="text-center text-uppercase">
                    <i class="fa fa-envelope"></i>Login to Vote
                </a>
            </button>
        {% endif %}
        <br />
      </div>
    </div>
  </div>
  
      

  <!-- <style>
    .container {
      border: 1px solid #ccc;
      padding: 20px;
      margin-bottom: 20px;
      display: flex;
      flex-direction: column;
      align-items: center;
    }

    .description {
      font-size: 18px;
      line-height: 1.5;
      color: #333;
      margin-bottom: 20px;
      text-align: center;
    }

    .button {
      background-color: blue;
      color: white;
      padding: 10px 20px;
      border: none;
      border-radius: 5px;
      text-decoration: none;
      display: block;
      cursor: pointer;
      transition: all 0.3s ease;
    }

    .button:hover {
      background-color: darkblue;
    }
  </style>
  <div class="container">
    <p class="description">
      This is a description of something.
    </p>
    <a href="https://www.example.com" class="button">Vote</a>
  </div> -->
          
                 
</body>
</html>