VotingProject/VotingHome/urls.py
from django.contrib import admin
from django.urls import include,path
from VotingHome import views

app_name = 'votinghome'
urlpatterns = [
    path('', views.signup, name='signup'),
    path('login-signup/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

VotingProject/VotingPolls/urls.py

# urls.py
from django.urls import path
from . import views

app_name = 'votingpolls'
urlpatterns = [
    path('', views.index, name='index'),
    # path('polls/', views.polls, name='polls'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    # path('all_results/', views.all_results, name='all_results'),
]


VotingProject/VotingProject/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('votinghome/', include('VotingHome.urls')),
    path('votingcontact/', include('VotingContact.urls')),
    path('', include('VotingWebsite.urls')),
    path('votingresult/', include('VotingResult.urls')),
    path('votingpolls/', include('VotingPolls.urls')),
    
]

VotingProject/VotingPolls/models.py
# models.py
from django.db import models
from datetime import datetime
from django.utils import timezone
from datetime import timedelta
from django.contrib.auth.models import User

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    # pub_date = models.DateTimeField(default=timezone.now)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text
    
class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
    voted_at = models.DateTimeField(auto_now_add=True)

    # class Meta:
    #     unique_together = ('user', 'question')

    def __str__(self):
        return f"{self.user} voted on {self.question}"

VotingProject/templates/polls/detail.html
{% load static %}
<link rel="stylesheet" href="{% static 'polls.css' %}">
{% include "pages/navbar.html" %}
<form action="{% url 'votingpolls:vote' question.id %}" method="post">
    {% csrf_token %}
    <br>
    <h1 style="text-align: center;">Vote attentively!</h1><br>
    <fieldset style="align-items: center;">
        <legend style="text-align: center;"><h1>{{question.question_text}}</h1></legend><br>
        {% if error_message %}
            <p style="text-align: center; color: red; font-weight: bold;"><strong>{{error_message}}</strong></p>
        {%endif%}<br>
        <div style="text-align: center;">
            {% if user_vote %}
            <p style="text-align: center; color: green; font-weight: bold;">You have already voted !</p>
            {% else %}
            {% for choice in question.choice_set.all %}
            <div style="display: inline-block; margin: 0 10px;">
                <input type="checkbox" name="choice" class="form-check-input" id="choice{{ forloop.counter }}"value="{{ choice.id }}"  style="display:block; margin: 0 auto;"/>
                <label for="choice{{ forloop.counter }}" style="display: block; text-align: center;">{{ choice.choice_text }}</label>
            </div>
            {% endfor %}
            {% endif %}
</div>
</fieldset>
<br>
<div style="text-align: center;">
    {% if not user_vote %}
    <input type="submit" value="Vote" class="option" />
    {% endif %}
</div>
</form>

VotingProject/templates/polls/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls.css' %}">
{% include "pages/navbar.html" %}
<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet">
<h1 class="heading">Vote on Your Favorite candidate
  <br>
  {% if user_vote  %}
    <span class="vote-status1" style="text-align: center;">You have Voted successfully!</span> 
  {% else %}
    <span class="vote-status2">You have not voted yet!</span>
{% endif %}
</h1>

<!-- Success message container -->
<section class="hero-section">
  <div id="success-message" class="success-message" style="display: none;">
    You have voted successfully!
  </div>
  <div class="card-grid">
    <a class="card" href="#">
      <div class="card__background" style="background-image: url(https://newsd.in/wp-content/uploads/2017/01/fghdcvcaku-1463668880-1479457960.jpg)"></div>
      <div class="card__content">
        <h3 class="card__heading">Bharatiya Janata Party (BJP)</h3>
      </div>
    </a>
    <a class="card" href="#">
      <div class="card__background" style="background-image: url(https://images.thequint.com/thequint/2020-02/1789abfc-53c9-41e2-bef6-20caaf95cef9/11021_pti2_11_2020_000079b.jpg?auto=format%2Ccompress&fmt=webp&w=1200)"></div>
      <div class="card__content">
        <h3 class="card__heading">Aam Aadmi Party (AAP) </h3>
      </div>
    </a>
    <a class="card" href="#">
      <div class="card__background" style="background-image: url(https://gumlet.assettype.com/nationalherald%2F2018-12%2Fb43c412e-bdf0-4405-81e7-660289ccb414%2Findian_national_congress_turns_134_years_of_age.jpg?rect=0%2C0%2C960%2C504&w=1200&auto=format%2Ccompress&fm=webp&ogImage=true)"></div>
      <div class="card__content">
        <h3 class="card__heading">Indian National Congress (INC)</h3>
      </div>
    </li>
    <a class="card" href="#">
      <div class="card__background" style="background-image: url(https://images.unsplash.com/photo-1557004396-66e4174d7bf6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60)"></div>
      <div class="card__content">
        <h3 class="card__heading">Bahujan Samaj Party (BSP)</h3>
      </div>
    </a>
  <div>
</section>
<div class="container">
    <h1 class="heading">Vote Now!</h1>
    <section class="question-section">
        <h2>"Which candidate or party do you believe will best address the pressing issues facing our community?"</h1><br>
        <h3>Note: Users can then select their preferred candidate or party from the list provided.</h3><br>
        
        <h1 class="text-center mb-3">Candidates</h1>
        {% if user_vote  %}
                <span class="vote-status1">You have already voted!</span>
        {% else %}
                <span class="vote-status2">You have not Voted yet!</span>
        {% endif %}
        <br>
        {% if latest_question_list %}
        <br>
          <ul>
            {% for question in latest_question_list %}
                {% if user_vote and user_vote.question == question %}
                <li class="voted-question">Voted: {{ question.question_text }}</li>
                {% else %}
                <li>
                  <a class="question {% if user_vote %} not-voted-question {% endif %}" 
                    {% if not user_vote %}href="{% url 'votingpolls:detail' question.id %}"{% endif %}>
                    {{ question.question_text }}
                  </a>
                </li>
                  
                {% endif %}
            {% endfor %}
          </ul>
        {% else %}
            <p>No polls available</p>
        {% endif %}
    </section>
</div>


  

VotingProject/templates/polls/polls.html
<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=<device-width>, initial-scale=1.0">
        <title>Polls Page</title>
</head>
<body>
    {% include 'pollingproject/nav.html'%}
    <h1> Polls PAge</h1>
</body>
</html> -->

VotingProject/templates/polls/results.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls.css' %}">
{% include "pages/navbar.html" %}
<br>
<h1 class="mb-5 text-center" style="text-align: center;">{{ question.question_text }}</h1>
<br>
<ul class="list-group mb-5" style="text-align: center;">
    {% for choice in question.choice_set.all %}
    <li class="list-group-item " style="display:block; font-size: 20px;">
        {{ choice.choice_text }} <span class="badge badge-success float-right">{{ choice.votes }}
            vote{{ choice.votes | pluralize }}</span>
    </li>
    {% endfor %}
</ul>
<br>
<br>
<div style="text-align: center; text-decoration: none;">
    <a class="results-button" href="{% url 'votingpolls:detail' question.id %}">Vote Again?</a>
</div>